language: php
php:
  - '7.2'
before_script:
  - mkdir ./bin
  # Download PHPCS
  - wget -O ./bin/phpcs https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  # Download PHP coveralls
  - wget -O ./bin/php-coveralls https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - chmod +x ./bin/phpcs ./bin/php-coveralls
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi -y
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f ci/vhost.conf /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart
  - curl http://127.0.0.1/ci/oauth.php
script:
  # Syntax check
  - find src -name "*.php" -print0 | xargs -0 -n1 php -l
  # Unit test
  - phpunit --coverage-clover ./test/clover.xml
  # Check code quality
  - ./bin/phpcs
after_script:
  - php ./bin/php-coveralls -v
